---
ping-pong:
  image: wrenywren/ping-pong
  ports:
    - "8080:80"

  environment:

    # ROUTING (for nginx-proxy container)
    #####################################
    VIRTUAL_HOST: ssl-test.mydomain.net
    LETSENCRYPT_HOST: ssl-test.mydomain.net
    LETSENCRYPT_EMAIL: devops+ssl@mydomain.net
